name: Python CI

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  test:
    name: Python test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Anaconda
        uses: conda-incubator/setup-miniconda@v1
        with:
          activate-environment: dpc
          environment-file: environment.yml
          python-version: 3.7
          auto-activate-base: false
      - name: Print environment
        shell: bash -l {0}
        run: |
          conda info
          conda list
          which pytest
          which mypy
      - name: Run Pytest
        run: python -m pytest
      - name: Run Type Check
        run: python -m mypy
